# Generated by Django 5.1.1 on 2024-12-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRANSPORTATION", "Transportation"),
                            ("HOUSING", "Housing"),
                            ("UTILITIES", "Utilities"),
                            ("HEALTHCARE", "Healthcare"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("SHOPPING", "Shopping"),
                            ("PERSONAL_CARE", "Personal Care"),
                            ("EDUCATION", "Education"),
                            ("TRAVEL", "Travel"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "payment_methods",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("DEBIT CARD", "Debit "),
                            ("CREDIT CARD", "Credit Card"),
                            ("BANK TRANSFER", "Bank Transfer"),
                            ("DIGITAL WALLET", "Digital Wallet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
