# Generated by Django 5.1.4 on 2025-01-07 14:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRANSPORTATION", "Transportation"),
                            ("HOUSING", "Housing"),
                            ("UTILITIES", "Utilities"),
                            ("HEALTHCARE", "Healthcare"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("SHOPPING", "Shopping"),
                            ("PERSONAL_CARE", "Personal Care"),
                            ("EDUCATION", "Education"),
                            ("TRAVEL", "Travel"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(db_index=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("DIGITAL_WALLET", "Digital Wallet"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expenses",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="expenses_ex_user_id_fe0ba0_idx"
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="expenses_ex_user_id_a540ff_idx",
                    ),
                ],
            },
        ),
    ]
