# Generated by Django 5.1.4 on 2025-01-07 14:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("SALARY", "Salary"),
                            ("FREELANCE", "Freelance"),
                            ("BUSINESS", "Business"),
                            ("INVESTMENTS", "Investment Income"),
                            ("RENTAL", "Rental Income"),
                            ("DIVIDEND", "Dividend"),
                            ("INTEREST", "Interest"),
                            ("BONUS", "Bonus"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                            ("INR", "Indian Rupee"),
                            ("CNY", "Chinese Yuan"),
                            ("CHF", "Swiss Franc"),
                            ("SGD", "Singapore Dollar"),
                            ("NZD", "New Zealand Dollar"),
                            ("HKD", "Hong Kong Dollar"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Source of income (e.g., employer name, client name)",
                        max_length=100,
                    ),
                ),
                (
                    "recurring",
                    models.BooleanField(
                        default=False, help_text="Whether this income occurs regularly"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONE_TIME", "One-Time"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("BIANNUALLY", "Bi-annually"),
                            ("ANNUALLY", "Annually"),
                        ],
                        help_text="Frequency of recurring income",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Incomes",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="income_inco_user_id_f74de7_idx"
                    ),
                    models.Index(
                        fields=["user", "income_type"],
                        name="income_inco_user_id_3966c1_idx",
                    ),
                    models.Index(
                        fields=["user", "recurring"],
                        name="income_inco_user_id_1c4ab3_idx",
                    ),
                    models.Index(
                        fields=["user", "currency"],
                        name="income_inco_user_id_35fc72_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="income_amount_positive",
                    )
                ],
            },
        ),
    ]
