# Generated by Django 5.1.4 on 2025-01-07 14:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "total_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget limit for the period",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "rollover_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable rolling over unused budget to next period",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRANSPORTATION", "Transportation"),
                            ("HOUSING", "Housing"),
                            ("UTILITIES", "Utilities"),
                            ("HEALTHCARE", "Healthcare"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("SHOPPING", "Shopping"),
                            ("PERSONAL_CARE", "Personal Care"),
                            ("EDUCATION", "Education"),
                            ("TRAVEL", "Travel"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "alert_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Percentage at which to trigger an alert",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notification_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="budget.budget",
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="BudgetNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("THRESHOLD_REACHED", "Threshold Reached"),
                            ("LIMIT_EXCEEDED", "Limit Exceeded"),
                            ("BUDGET_RESET", "Budget Reset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "budget_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="budget.budgetcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "start_date"], name="budget_budg_user_id_b2e1d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "period"], name="budget_budg_user_id_6ecba7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetcategory",
            unique_together={("budget", "category")},
        ),
        migrations.AddIndex(
            model_name="budgetnotification",
            index=models.Index(
                fields=["budget_category", "created_at"],
                name="budget_budg_budget__f2552e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetnotification",
            index=models.Index(
                fields=["budget_category", "read"],
                name="budget_budg_budget__87c0e5_idx",
            ),
        ),
    ]
